require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/MethodLength:
  Exclude:
    - "config/*.rb"
    - "db/migrate/*.rb"

Style/Documentation:
  Enabled: false
